chore: switch to lix, update nix_copy_s3.py (#45)
Given the determinate systems installer is about to drop upstream nix
and the upstream fork of
[nix-installer](https://github.com/NixOS/nix-installer) being
experimental, it's time to just move. The repo and cache are still
compatible with CppNix and DetNix, so this really doesn't matter much.

`nix_copy_s3.py` has been updated to support both Nix and Lix; but also
to optionally query the final cache so we avoid the costly `nix copy`
step if a package has not changed.

diff --git a/.github/actions/nix_sign_cache_s3/action.yml b/.github/actions/nix_sign_cache_s3/action.yml
--- a/.github/actions/nix_sign_cache_s3/action.yml
+++ b/.github/actions/nix_sign_cache_s3/action.yml
@@ -1,10 +1,10 @@
 name: Sign & Cache Nix Build (S3)
 description: |
   Caches any Nix builds in AWS S3.
-  
+
   Requires Nix and AWSCLI to both be installed in the calling workflow
   beforehand.
-  
+
   Requires Nix builds to have actually occurred beforehand.
 inputs:
   shell:
@@ -56,7 +56,7 @@ runs:
         umask 077
         echo "${{ inputs.nix_private_key }}" > ~/nix-private-key
         for output in ${{ inputs.flake_outputs }}; do
-          nix store sign --recursive --key-file ~/nix-private-key $output && echo "Successfully signed $output" || echo "Failed to sign $output"
+          nix store sign --recursive --key-file ~/nix-private-key $output && echo "Successfully signed $output" || echo "Failed to sign $output - skipping"
         done
     - name: Push to S3 Cache
       shell: ${{ inputs.shell }}
@@ -64,6 +64,7 @@ runs:
       run: |
         python3 ${{ github.action_path }}/nix_copy_s3.py \
           --upstream-cache "https://cache.nixos.org" \
+          --upstream-cache "TARGET_HTTPS" \
           --to-s3-bucket "${{ inputs.s3_bucket_name }}" \
           --verify-signature-key "${{ inputs.nix_public_key }}" \
           ${{ inputs.flake_outputs }}
